### ISSUE TITLE
Implement support for GitHub Actions Job Summaries

### ISSUE THREAD

**Issue by lzaoral** [redhat-plumbers-in-action/differential-shellcheck#14]
Recently, GA gained support for job summaries which might serve as a nice way to visualise the problems found by Shellcheck.

See: https://github.blog/2022-05-09-supercharging-github-actions-with-job-summaries/

**Comment by jamacku** [comment]
@lzaoral Thank you, looks like something that would make sense to implement here, I'll definitely have a closer look.
