### ISSUE TITLE
New GitHub Code Scanning feature makes unwanted comments on each PR

### ISSUE THREAD

**Issue by jamacku** [redhat-plumbers-in-action/differential-shellcheck#215]
### Type of issue

Bug Report

### Description

New GitHub feature announced via blog - [Code scanning shows more accurate and relevant alerts on pull requests](https://github.blog/changelog/2023-03-17-code-scanning-shows-more-accurate-and-relevant-alerts-on-pull-requests/)

![image](https://user-images.githubusercontent.com/2879818/226088323-89acd132-5151-4950-94ff-cb8eb7d5adc4.png)

Example:

- https://github.com/systemd/systemd/pull/26875

### Describe the solution you'd like

We should probably check what GitHub means by "The change ensures code scanning only shows accurate and relevant alerts for the pull request" and by "Now, the tool reports only alerts inside the lines of code that the pull request has changed, which makes it easier to fix these contextualized alerts in a timely manner." Is GitHub doing differential reports now?

Maybe using the official way how to upload SARIF will solve our issue: https://github.com/github/codeql-action/blob/v2/upload-sarif/action.yml

**Comment by evverx** [comment]
> Maybe using the official way how to upload SARIF will solve our issue

I think it should probably help but looking https://github.com/search?q=%22As+part+of+the+setup+process%2C+we+have+scanned+this+repository+and+found+no+existing+alerts.%22&type=issues it seems GitHub just broke actions that don't look like CodeQL to cater to CodeQL and that wasn't very nice probably.

**Comment by evverx** [comment]
I think it could be that GH shows this because there are no shellcheck alerts in the systemd repository and because of that GH assumes that the action has just been introduced. If that is the case it's probably a GH bug.

**Comment by jamacku** [comment]
Yes, It seems like a GH bug. Im going to do some testing to see if I can find some workaround. Thanks for looking into this @evverx

**Comment by jamacku** [comment]
Ok, so I think the way how to fix it, at least for the `systemd` repo, is to trigger workflow on `push` as well.

current config: - https://github.com/jamacku/systemd/pull/72
with `on: push`: - https://github.com/jamacku/systemd/pull/74

I'll prepare PR.

**Comment by praiskup** [comment]
> Ok, so I think the way how to fix it, at least for the systemd repo, is to trigger workflow on push as well.

Is this a workaround, or a real fix?  Has this been reported as GitHub issue?

**Comment by evverx** [comment]
For that new GH feature to work it has to be able to compare PRs with the "main" branch so I'd say it's a real fix in the sense that it makes the action compatible with that feature. To get rid of those annoying comments GH would have to somehow special case actions that run on PRs only and I don't think GH is particularly interested in it (because it would most likely involve partially rolling back that feature or allowing certain actions to opt-out). I don't know if it has been reported or not but looking at the number of the comments I think GH is aware of them.

**Comment by jamacku** [comment]
@evverx, @praiskup FYI, It seems like GitHub changed the way how it detects the introduction of new scanning tools, and it no longer requires running ShellCheck/PyLint on a `push` event.

- https://github.com/systemd/mkosi-initrd/pull/29
- https://github.com/systemd/mkosi-initrd/pull/29/files#diff-eace62a8ebcdafd0f6975200d68cbf851300952aae47db07e71f383038a368b3L6-L8

**Comment by evverx** [comment]
@jamacku good to know. Thanks! I think actions still should be triggered on push events to get diffs. My guess would be that without that all alerts would be "new" and invisible for external contributors.
