### ISSUE TITLE
bot is creating comments on every PR

### ISSUE THREAD

**Issue by cgwalters** [redhat-plumbers-in-action/differential-shellcheck#222]
### Type of issue

Bug Report

### Description

The bot started to comment on every pull request opened saying the workflow is new, when it's not:
https://github.com/coreos/rpm-ostree/pull/4344#issuecomment-1481203675

### Describe the solution you'd like

It didn't used to do this, please stop.

**Comment by jamacku** [comment]
I am closing this issue since the comment no longer appears in new PRs. Feel free to reopen if you experience this issue again or follow on:

- https://github.com/redhat-plumbers-in-action/differential-shellcheck/issues/215
