### ISSUE TITLE
exclude-path does not accept a list as documented

### ISSUE THREAD

**Issue by VladimirSlavik** [redhat-plumbers-in-action/differential-shellcheck#309]
### Type of issue

Bug Report

### Description

Docs say that `exclude-path` is a "_List of relative paths (...)_" : https://github.com/redhat-plumbers-in-action/differential-shellcheck#exclude-path

However, a list...
```
exclude-path:
  - '*.j2'
  - '**/*.j2'
```
...  is not accepted: https://github.com/rhinstaller/anaconda/actions/runs/6072006299/workflow

### Describe the solution you'd like

Please describe how to specify more than one path.

**Comment by VladimirSlavik** [comment]
So, I checked more, and it seems the "bug" is that the docs (README) are not verbose enough.

The docs just say it's a "list".

Most actions (that I know) take a list as a YAML list:
```
something:
  - one
  - two 
  - three
```
Or the shorter syntax: `something: [one, two, three]`.

This action takes instead a multi-line string:
```
something: |
  one
  two
  three
```

The issue is that the examples show only the syntax for one item, which is the same for both variants:
```
something: only-value
```

The fix would be to extend the docs a bit to say it's a list in a multi-line string, same as `run` in gh actions, and add an example of the multi-line/value syntax.

(Of course, reading the code. it's evident that the value is passed as an environment variable, so it must be a string...)

**Comment by jamacku** [comment]
I'm sorry you have got hit, but this. I see you managed to sort it on your own. Thank you for your contribution. :+1:

**Comment by jamacku** [comment]
Oh, you are right. Please ignore my previous comment.

I accidentally swapped the option `exclude-path` for the newly added `scan-directory` option.
