### ISSUE TITLE
Make the shell detection from hashbang more general

### ISSUE THREAD

**Issue by lzaoral** [redhat-plumbers-in-action/differential-shellcheck#68]
### Type of issue

Feature Request

### Description

At the moment, the action checks explicitly only for `  #!/bin/bash` and `#!/bin/sh`:
https://github.com/redhat-plumbers-in-action/differential-shellcheck/blob/41f6a1e3e9f44e0710576c25224f5c42d898a3e2/src/functions.sh#L38-L43

This, however, does not take into consideration possible white spaces (e.g. `␣#!␣␣/bin/bash`, ...), different paths (e.g. `#!/usr/bin/bash` or `#!/usr/local/bin/bash`, ...) or a possibility to execute the shell from `PATH` (e.g. `#!/bin/env bash`, ...), and maybe other variations I didn't come up with yet.

### Describe the solution you'd like

Fix all shortcomings mentioned above.

**Comment by jamacku** [comment]
Thank you for reporting this issue. I will have a look once I have time.

**Comment by lzaoral** [comment]
This ShellCheck's function might be useful: https://github.com/koalaman/shellcheck/blob/ade2bf7b871362c9c30878294aef8ab775f3ea07/src/ShellCheck/Parser.hs#L3114

**Comment by lzaoral** [comment]
We could also scan the scripts for the e.g. `shellcheck shell=bash` directives.

**Comment by jamacku** [comment]
Also: `#!/usr/bin/env bash` - [@rbenv/rbenv](https://github.com/rbenv/rbenv)
