### ISSUE TITLE
ShellCheck should follow external resources by default

### ISSUE THREAD

**Issue by mrc0mmand** [redhat-plumbers-in-action/differential-shellcheck#89]
### Type of issue

Bug Report

### Description

The Differential ShellCheck action should follow external sources by default (by using `-x/--external-sources` shellcheck option), otherwise it causes "bogus" alerts like:

![image](https://user-images.githubusercontent.com/679338/184991660-50c533e7-60f5-4655-b419-721ae16a95bf.png)

For example, SuperLinter's shellcheck does this by default, see: https://github.com/github/super-linter/blob/f1196a50f6ee029f612f19dd5d3d7b95b22928b5/lib/linter.sh#L887

### Describe the solution you'd like

Differential ShellCheck should pass the `-x/--external-sources` option to shellcheck.

**Comment by jamacku** [comment]
I agree that current behavior is unfortunate, you can enable external sources using `.shellcheckrc`:

```sh
external-sources=true
```

I'm going to enable it by default in the new major version.
